export const fakeRawChannels = [
  {
    id: 'C001',
    name: 'general',
    is_channel: true,
    is_private: false,
    is_im: false,
    is_mpim: false,
    is_member: true,
    num_members: 42,
  },
  {
    id: 'C002',
    name: 'random',
    is_channel: true,
    is_private: false,
    is_im: false,
    is_mpim: false,
    is_member: false,
    num_members: 100,
  },
  {
    id: 'G001',
    name: 'my-private',
    is_channel: false,
    is_private: true,
    is_im: false,
    is_mpim: false,
    is_member: true,
    num_members: 5,
  },
  {
    id: 'D001',
    name: undefined,
    is_channel: false,
    is_private: false,
    is_im: true,
    is_mpim: false,
    is_member: true,
    user: 'U999',
  },
  {
    id: 'G002',
    name: 'mpdm-alice--bob',
    is_channel: false,
    is_private: false,
    is_im: false,
    is_mpim: true,
    is_member: true,
    num_members: 3,
  },
];
